# Use the official ASP.NET Core runtime as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Use the official ASP.NET Core SDK as a parent image
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["PostTestSERA/PostTestSERA.csproj", "PostTestSERA/"]
RUN dotnet restore "PostTestSERA/PostTestSERA.csproj"
COPY . .
WORKDIR "/repos/PostTestSERA"
RUN dotnet build "PostTestSERA.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PostTestSERA.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PostTestSERA.dll"]